---
title: "Project Description Outline"
author: "Team KLAS"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# **Name of Dashboard**

### Members of Team KLAS

* Aboubakar Hameed
* Kang Hin Lee
* Lucy Burns
* Seàn M. Cusick

### Roles & responsibilities of each member

* **Aboubakar Hameed** was responsible for `Work Package 2.3 - Shiny App`; furthermore, supported <spatial visualisations>, <data cleaning>,... 

* **Kang Hin Lee** was responsible for `Work Package 2.1 - Data Analysis`; furthermore, supported <spatial visualisations>, <data cleaning>,... 

* **Lucy Burns** was responsible for `Work Package 2.2 - Data Analysis`; furthermore, supported <spatial visualisations>, <data cleaning>,... 

* **Seàn M. Cusick** was responsible for  `Work Package 1 - Project Management` & `Work Package 3 - Documentation`; furthermore, supported <spatial visualisations>, <data cleaning>,...  

* **All team members** worked on the following **Work Packages** (WP):  
  * `WP1.1 - Project Set-up`  
  * `WP2 - Shiny App MVP`  
  * `WP2.1.1 - DataSet Selection ` 
  * `WP2.1.2 - Data Cleaning`  
  * `WP2.1.3 - Data Wrangling`  
  * `WP2.2.1 - Temporal Visualisations`  
  * `WP2.2.2 - Spatial Visualisations`  
  * `WP2.2.3 - Demographic Visualisations`  
  * `WP2.3.1 - User Interface`  
  * `WP2.3.2 - Backend Code`  
  * `WP3.1 - Report`  
  * `WP3.1.1 - Analysis`  
  * `WP3.1.2 - README File`  
  * `WP3.2 - Presentation`  
   

### Brief description of dashboard topic

Our dashboard contains three sections:
1. checkboxes of each health board
2. drop down menu for individual hospitals in that health board
3. Tabs
  1). Map of Scotland
  2). Time series graphs
  3). proportional graphs
  
additionally, a number of buttons such as:
* reset
* select all

Our topic is ...

The dashboard outlines our topic in terms of ...

***  

### Stages of the project

* Role Allocation  
* Project Management  
  * Work Breakdown Structure  
  * Project Gantt  
  * Git branching  
  * Version control  
* Application Development  
  * Choosing datasets  
  * Dashboard wireframe  
***

#### **Role Allocation**

asdf

#### **Project Management**

asdf


##### Work Breakdown Structure

asdf


##### Project Gantt

asdf


##### Git branching

asdf


##### Version Control

asdf


#### **Application Development**

asdf


##### Dataset Selection

asdf

##### Dashboard wireframe

asdf

***

### Which tools were used in the project

* Discord (daily stand-ups, occasional mob programming, sharing ideas and links)
* GitHub/Projects (Project Management - Kaban Board)
* Git/GitHub (collaboration & version control)
* Microsoft Word (Work Breakdown Structure
* Microsoft Excel (Gantt Chart)

and so on ...

### How did you gather and synthesise requirements for the project?

We synthesised the information given in the brief by ...

We prioritised ...

### Motivations for using the data you have chosen

We used the dataset on ... to answer ... and because it was ...

### Data quality and potential bias, including a brief summary of data cleaning and transformations

According to the About tab on the dataset page/dedicated page online, the data quality ...

The dataset may/may not be biased because ...

To clean the datasets we ...

### How is the data stored and structured

[**Hint**: This page offers a good starting point for understanding the data structure: https://guides.statistics.gov.scot/article/34-understanding-the-data-structure]

The data is in the form of ...

This means ...

Benefits of storing the data like this are ...

### Ethical and legal considerations of the data

[**Hint:** this page contains information on the Open Government License which covers most datasets on statistics.gov.scot: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/]

There are no/There may be ethical considerations, because ...

The datasets are covered by the Open Government License, which means ...