---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(rgdal)
library(here)
library(broom)
```

```{r}
ane_weekly_full <- read_csv(here("clean_data/df_ane_hb_ans.csv"))
```

```{r}
ane_weekly <- ane_weekly_full %>% 
  filter(sex == "All" & age_group == "All ages")
```

```{r}
ane_weekly %>% 
  group_by(hb) %>% 
  summarise(count = n())
```

```{r}
ane_weekly <- ane_weekly %>% 
  mutate(hb_name = case_when(
	        hb == "S92000003" ~ "Scotland",
	        hb == "S08000015" ~ "Ayrshire and Arran",
	        hb == "S08000016" ~ "Borders",
	        hb == "S08000017" ~ "Dumfries and Galloway",
	        hb == "S08000019" ~ "Forth Valley",
	        hb == "S08000020" ~ "Grampian",
	        hb == "S08000022" ~ "Highland",
	        hb == "S08000024" ~ "Lothian",
	        hb == "S08000025" ~ "Orkney",
	        hb == "S08000026" ~ "Shetland",
	        hb == "S08000028" ~ "Western Isles",
	        hb == "S08000029" ~ "Fife",
	        hb == "S08000030" ~ "Tayside",
        	hb == "S08000031" ~ "Greater Glasgow and Clyde",
	        hb == "S08000032" ~ "Lanarkshire",
	TRUE ~ as.character(NA))) %>% 
  group_by(hb_name, year, week_ending, number_attendances) 
```

```{r}
ane_weekly <- ane_weekly %>% 
  filter(hb_name != "Scotland")
```

```{r}
ane_weekly_trend <- ane_weekly %>% 
    arrange(hb_name) %>% 
      group_by(year, week_ending, hb_name) %>% 
  summarise(number_attendances = sum(number_attendances)) %>%   
      mutate(
    moving_avg = slide_dbl(
      .x = number_attendances,
      .f = ~mean(.,na.rm = TRUE),
# 2 weeks moving average
      .before = 2
    )  )
ane_weekly_trend %>% 
  ggplot()+
  aes(x = week_ending, y = moving_avg, group = hb_name, colour = hb_name)+
  geom_line()+
  labs(title = "2 Weeks Moving Average Hospital A&E attendance",
       subtitle = "by Health Board\n",
       colour = "Health Board\n") +
  xlab("Time (date)")+
  ylab("Average Attendance Count") +
 # scale_color_brewer(palette = "Paired") +
  theme(panel.background = element_rect(fill = 'gray82')) +
  theme(
    legend.position = "bottom",
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.text = element_text(colour="slategray", size=8)
    )
```