---
title: "phs_rshiny_dashboard_project_main"
output: html_notebook
---

# Packages
#--------------------------------------------------------------------------#
```{r, echo=FALSE, message=FALSE, results='hide'}
library(tidyverse)
library(sf)
library(janitor)
library(jsonlite)
library(lubridate)
library(rgdal)
library(here)
library(broom)
require(readr)
require(here)
```

# API Function
#--------------------------------------------------------------------------#

```{r, echo=FALSE, message=FALSE, results='hide'}
# Function for fetching phs dataframes
phs_df_func <- function(id){
  
  # Link templates for simplicity
  phs_url = "https://www.opendata.nhs.scot/api/3/action/datastore_search?resource_id="
  # fetch maximum 999'999 results for simplicity
  limit_url = "&limit=999999"
  
  # construct URL for fetching process
  url_link <- paste0(phs_url, id, limit_url) %>%
    fromJSON()
  
  # construct dataframe from url
  phs_df <-  url_link[["result"]][["records"]] %>% 
    clean_names()
  
  return(phs_df)

}


phs_dictionary_func <- function(id){
  
  # Link templates for simplicity
  phs_url = "https://www.opendata.nhs.scot/api/3/action/datastore_search?resource_id="
  # fetch maximum 999'999 results for simplicity
  limit_url = "&limit=10"
  
  # construct URL for fetching process
  url_link <- paste0(phs_url, id, limit_url) %>%
    fromJSON()
  
  # construct dataframe from url
  phs_dictionary <-  url_link[["result"]][["fields"]] %>% 
    jsonlite::flatten(recursive = TRUE) %>% 
    select(id, info.label, type)
  #    jsonlite::flatten(recursive = TRUE, use.names = TRUE)

  return(phs_dictionary)
}

```

# PHS API (ID)
#--------------------------------------------------------------------------#
```{r, echo=FALSE, message=FALSE, results='hide'}
# Data Group 00 -  Location / ID Identifier ----
# Hospital LOCATION List
api_hospital_location = "c698f450-eeed-41a0-88f7-c1e40a568acc"
# Health Board List (Health Board)
api_health_board = "652ff726-e676-4a20-abda-435b98dd7bdc"
api_special_health_board = "0450a5a2-f600-4569-a9ae-5d6317141899"
# HSCP List 
api_hscp = "944765d7-d0d9-46a0-b377-abb3de51d08e"
####
####
####
# Data Group 01 - Hospital Activity ----
# Dataset 1A - Hospital Activity by Speciality
api_ha_spe = "c3b4be64-5fb4-4a2f-af41-b0012f0a276a" 
# Dataset 1B - Hospital Activity and Patient Demographics
api_ha_ans = "00c00ecc-b533-426e-a433-42d79bdea5d4"
# Dataset 1C - Hospital Activity and Deprivation
api_ha_dep = "4fc640aa-bdd4-4fbe-805b-1da1c8ed6383"
####
####
####
# Data Group 02 - Hospitalisations due to Covid 19 ----
# Dataset 2A - Admissions By Health Board and Specialty
api_cov_hb_spe = "b8aeb539-fcf8-4f66-aae8-20213508a1b7"
# Dataset 2B - Admissions By Health Board and Patient Demographics
api_cov_hb_ans = "f8f3a435-1925-4c5a-b2e8-e58fdacf04bb"
# Dataset 2C - Admissions By Health Board and Deprivation
api_cov_hb_dep = "746f9bac-77f1-43fe-b69f-5ca2cde2201b"
# Dataset 2D - Admissions By HSCP and Specialty
api_cov_hscp_spe =  "02696773-7aaf-48ce-b3d5-479d86fc8334"
# Dataset 2E - Admissions By HSCP and Patient Demographics
api_cov_hscp_ans = "aec5cc00-3ad6-41fb-9101-37c66bad29d4"
# Dataset 2F - Admissions By HSCP and Deprivation
api_cov_hscp_dep = "95a324b3-7610-4151-9287-ccd9cb191686"
####
####
####
# Data Group 03 -  A&E Activity  ----
# A&E Activity by Health Board, Age and Sex
api_ane_hb_ans = "388fd86c-dc0b-4655-b4b1-f13644bfd8d2"
# A&E Activity by Health Board and Deprivation
api_ane_hb_dep = "ec70ded6-9f45-4348-aaa9-b1b40ddae6a4"
# A&E Activity by HSCP, Age and Sex
api_ane_hscp_ans =  "a5677672-cc57-4b36-a884-84d6befd570f"
# A&E Activity by HSCP and Deprivation
api_ane_hscp_dep =  "39da7e8d-0ecf-41b7-aef1-cd898ba8b4fa"
####
####
####
# Data Group 04 - Bed Capacity ----
# Beds by Board of Treatment and Specialty
api_bed_info = "f272bb7d-5320-4491-84c1-614a2c064007"

####
####
####
# Data Group 05 - COVID-19 Wider Impacts - Scottish Ambulance Services ----
# SAS Incidents By Health Board, Age and Sex
api_sas_health_board_age_sex = "d1d2d098-193f-489c-940a-a828fdcfc357"
# SAS Incidents By Health Board and Deprivation
api_sas_health_deprivation = "12e52d78-bff5-4fde-8085-f1b03667a8e5"
# SAS Incidents By HSCP, Age and Sex
api_sas_hscp_age_sex = "0a3992c3-a712-4adf-b3b3-928850cc65ff"
# SAS Incidents By HSCP and Deprivation
api_sas_hscp_deprivation = "1329dfdb-0dd7-428b-9afb-b8fb3e438518"
####
####
####
# Data Group 06 - Daily COVID-19 Cases in Scotland ----
# Total Cases By Health Board
api_total_cov_health_board = "7fad90e5-6f19-455b-bc07-694a22f8d5dc"
# Total Cases By Local Authority
api_total_cov_local_authority = "e8454cf0-1152-4bcb-b9da-4343f625dfef"
# Total Cases By Age and Sex
api_total_cov_age_sex = "19646dce-d830-4ee0-a0a9-fcec79b5ac71"
# Total Cases By Deprivation
api_total_cov_deprivation = "a965ee86-0974-4c93-bbea-e839e27d7085"
# Daily and Cumulative Cases
api_daily_cumulative_cov = "287fc645-4352-4477-9c8c-55bc054b7e76"
# Daily Case Trends By Health Board
api_daily_trends_health_board = "2dd8534b-0a6f-4744-9253-9565d62f96c2"
# Daily Case Trends By Local Authority
api_daily_trends_local_authority = "427f9a25-db22-4014-a3bc-893b68243055"
# Seven day trends by Neighbourhood
api_seven_day_trends_neighbourhood = "8906de12-f413-4b3f-95a0-11ed15e61773"
# Daily Case Trends By Age and Sex
api_daily_trend_age_sex = "9393bd66-5012-4f01-9bc5-e7a10accacf4"
# Daily Case Trends By Deprivation
api_daily_trend_deprivation = "a38a4c21-7c75-4ecd-a511-3f83e0e8f0c3"
####
####
####
# Total Cases By Deprivation ----
api_sco_cov_total_deprivation = "a965ee86-0974-4c93-bbea-e839e27d7085"
####
####
####
# Daily Case Trends By Deprivation -----
api_sco_dov_daily_deprivation = "a38a4c21-7c75-4ecd-a511-3f83e0e8f0c3"
####
####
####
#Sample DF Reader (Press Ctrl+Shift+C to uncomment) ----
# sample_DF <- phs_df_func(api_bed_info)
# view(sample_DF)
```

# Load in API Dataframe (Backup)
#--------------------------------------------------------------------------#
```{r}
# Data Group 00 - Hospital Location Info
backup_hospital_location = phs_df_func(api_hospital_location)
backup_health_board = phs_dictionary_func(api_health_board)

# Data Group 01
# Dataset 1A - Hospital Activity by Speciality
backup_ha_spe = phs_df_func(api_ha_spe)
# Dataset 1B - Hospital Activity and Patient Demographics
backup_ha_ans = phs_df_func(api_ha_ans)
# Dataset 1C - Hospital Activity and Deprivation
backup_ha_dep = phs_df_func(api_ha_dep)


# Data Group 02
# Hospitalisations due to Covid 19
# Dataset 2A - Admissions By Health Board and Specialty
backup_cov_hb_spe = phs_df_func(api_cov_hb_spe)
# Dataset 2B - Admissions By Health Board and Patient Demographics
backup_cov_hb_ans = phs_df_func(api_cov_hb_ans)
# Dataset 2C - Admissions By Health Board and Deprivation
backup_cov_hb_dep = phs_df_func(api_cov_hb_dep)
# Dataset 2D - Admissions By HSCP and Specialty
backup_cov_hscp_spe = phs_df_func(api_cov_hscp_spe)
# Dataset 2E - Admissions By HSCP and Patient Demographics
backup_cov_hscp_ans = phs_df_func(api_cov_hscp_ans)
# Dataset 2F - Admissions By HSCP and Deprivation
backup_cov_hscp_dep = phs_df_func(api_cov_hscp_dep)


# Data Group 03 
# A&E Activity by Health Board, Age and Sex
backup_ane_hb_ans <- phs_df_func(api_ane_hb_ans)
# A&E Activity by Health Board and Deprivation
backup_ane_hb_dep <- phs_df_func(api_ane_hb_dep)
# A&E Activity by HSCP, Age and Sex
backup_ane_hscp_ans =  phs_df_func(api_ane_hscp_ans)
# A&E Activity by HSCP and Deprivation
backup_ane_hscp_dep =  phs_df_func(api_ane_hscp_dep)


# Data Group 04 - Bed Capacity
# Beds by Board of Treatment and Specialty
backup_bed_info = phs_df_func(api_bed_info)
#

# Data Group 05 - COVID-19 Wider Impacts - Scottish Ambulance Services ----
backup_sas_health_board_age_sex = phs_df_func(api_sas_health_board_age_sex)
backup_sas_health_deprivation = phs_df_func(api_sas_health_deprivation)
backup_sas_hscp_age_sex = phs_df_func(api_sas_hscp_age_sex)
backup_sas_hscp_deprivation = phs_df_func(api_sas_hscp_deprivation)
####
####
####
# Data Group 06 - Daily COVID-19 Cases in Scotland ----
backup_total_cov_health_board  = phs_df_func(api_total_cov_health_board)
backup_total_cov_local_authority = phs_df_func(api_total_cov_local_authority)
backup_total_cov_age_sex = phs_df_func(api_total_cov_age_sex)
backup_total_cov_deprivation = phs_df_func(api_total_cov_deprivation)
backup_daily_cumulative_cov = phs_df_func(api_daily_cumulative_cov)
backup_daily_trends_health_board = phs_df_func(api_daily_trends_health_board)
backup_daily_trends_local_authority = phs_df_func(api_daily_trends_local_authority)
backup_seven_day_trends_neighbourhood = phs_df_func(api_seven_day_trends_neighbourhood)
backup_daily_trend_age_sex = phs_df_func(api_daily_trend_age_sex)
backup_daily_trend_deprivation = phs_df_func(api_daily_trend_deprivation)
####
####
####
# Total Cases By Deprivation ----
backup_sco_cov_total_deprivation = phs_df_func(api_sco_cov_total_deprivation)
####
####
####
# Daily Case Trends By Deprivation -----
backup_sco_dov_daily_deprivation = phs_df_func(api_sco_dov_daily_deprivation)



```


# Cleaning & Merging Dataset
#--------------------------------------------------------------------------#

## Data Group 00 - Hospital Location
```{r}
# Hospital Location
df_hospital_location <-  backup_hospital_location %>%
  select(-ends_with("qf"), -id) %>% 
 mutate(x_coordinate = replace_na(x_coordinate, 327699),
         y_coordinate = replace_na(y_coordinate, 669148))
  
  
df_lat_long_convert <- df_hospital_location %>%
  st_as_sf(coords = c("x_coordinate", "y_coordinate"), crs = 27700) %>%
  st_transform(4326) %>%
  st_coordinates() %>%
  as_tibble() %>% 
  rename(longitude = X,
        latitude = Y)
  
df_hospital_location <- df_hospital_location %>% 
  bind_cols(df_lat_long_convert)
  
# function to assign hospital name, longitude & latitude to dataframe
# hospital_location_func(datafram, "key column")
hospital_location_func <- function(df, key_col){
            df <- df %>% 
            # Select location & hb as forgein keys
            # Join location_name, longitude & latitude to the main dataframe
            left_join(df_hospital_location %>% select(key_col, location_name, longitude, latitude),
            by = c(key_col),
            all.x = TRUE)
            
            return(df)
}


df_health_board <- backup_health_board
# 
# NHSBoards <- readOGR(dsn = "SG_NHS_HealthBoards_2019.shp", 
#                      layer = "SG_NHS_HealthBoards_2019")

```

## Data Group 01 - Hospital Activity
```{r}
# clean_quart_df_func(dataframe)
clean_quart_df_func <- function(df){
                df <- df %>% 
                select(-ends_with("qf"), -id) %>% 
                mutate(year = substr(quarter, 1,4),
                quarter = substr(quarter,nchar(quarter), nchar(quarter))) %>% 
                # Relocate the year and quarter columns to the start
                relocate(c("year" ,"quarter"), .before = 1)
                # Return cleaned dataframe
                return(df)
}

# Dataset 1A - Hospital Activity by Speciality
df_ha_spe <- clean_quart_df_func(backup_ha_spe)
# Dataset 1B - Hospital Activity and Patient Demographics
# change column "age" to "age_group" for consisitency
df_ha_ans <- clean_quart_df_func(backup_ha_ans) %>% 
    rename(age_group = age)
# Dataset 1C - Hospital Activity and Deprivation
df_ha_dep <- clean_quart_df_func(backup_ha_dep) 


```

## Data Group 02 - Hospitalisations due to Covid 19
```{r}
# Clean Hospitalisations Dataset function
clean_wkend_df_func <- function(df){
                  df <- df %>% 
                  # Remove any columns ends with qf (Qualifier)
                  select(-ends_with("qf"), -id) %>% 
                  # Extract he quarter, year info from week_ending
                  mutate(week_ending = as.Date(ymd(week_ending)),
                         quarter     = quarter(week_ending),
                         year        = year(week_ending)) %>% 
                  # Relocate the year and quarter columns to the start
                  relocate(c("year" ,"quarter"), .before = 1)
                  # Return cleaned dataframe
                  return(df)
}

# Dataset 2A - Admissions By Health Board and Specialty
df_cov_hb_spe  <- clean_wkend_df_func(backup_cov_hb_spe)
# Dataset 2B - Admissions By Health Board and Patient Demographics
df_cov_hb_ans <- clean_wkend_df_func(backup_cov_hb_ans)
# Dataset 2C - Admissions By Health Board and Deprivation
df_cov_hb_dep <- clean_wkend_df_func(backup_cov_hb_dep)
# Dataset 2D - Admissions By HSCP and Specialty
df_cov_hscp_spe <- clean_wkend_df_func(backup_cov_hscp_spe)
# Dataset 2E - Admissions By HSCP and Patient Demographics
df_cov_hscp_ans <- clean_wkend_df_func(backup_cov_hscp_ans)
# Dataset 2F - Admissions By HSCP and Deprivation
df_cov_hscp_dep <- clean_wkend_df_func(backup_cov_hscp_dep)

```

##Data Group 03 - A&E Activity
```{r}
# Data Group 03 -  A&E Activity

# A&E Activity by Health Board, Age and Sex
df_ane_hb_ans <- clean_wkend_df_func(backup_ane_hb_ans)

# A&E Activity by Health Board and Deprivation
df_ane_hb_dep <- clean_wkend_df_func(backup_ane_hb_dep)
# A&E Activity by HSCP, Age and Sex
df_ane_hscp_ans <-  clean_wkend_df_func(backup_ane_hscp_ans)
# A&E Activity by HSCP and Deprivation
df_ane_hscp_dep <-  clean_wkend_df_func(backup_ane_hscp_dep)


```


## Data Group 04 - Hospital Bed Information
```{r}
df_bed_info <- clean_quart_df_func(backup_bed_info)
```


```{r}
# Data Group 05 - COVID-19 Wider Impacts - Scottish Ambulance Services ----
df_sas_health_board_age_sex <- backup_sas_health_board_age_sex
df_sas_health_deprivation <- backup_sas_health_deprivation
df_sas_hscp_age_sex <- backup_sas_hscp_age_sex
df_sas_hscp_deprivation <- backup_sas_hscp_deprivation
####
####
####
# Data Group 06 - Daily COVID-19 Cases in Scotland ----
df_total_cov_health_board <- backup_total_cov_health_board
df_total_cov_local_authority <- backup_total_cov_local_authority
df_total_cov_age_sex <- backup_total_cov_age_sex
df_total_cov_deprivation <- backup_total_cov_deprivation
df_daily_cumulative_cov <- backup_daily_cumulative_cov
df_daily_trends_health_board <- backup_daily_trends_health_board
df_daily_trends_local_authority <- backup_daily_trends_local_authority
df_seven_day_trends_neighbourhood <- backup_seven_day_trends_neighbourhood
df_daily_trend_age_sex <- backup_daily_trend_age_sex
df_daily_trend_deprivation <- backup_daily_trend_deprivation
####
####
####
# Total Cases By Deprivation ----
df_sco_cov_total_deprivation <- backup_sco_cov_total_deprivation
####
####
####
# Daily Case Trends By Deprivation -----
df_sco_dov_daily_deprivation <- backup_sco_dov_daily_deprivation
```








## Age & Sex Data Frame related
```{r}
age_group_ha_ans <- df_ha_ans %>% 
    mutate(age_group = factor(age_group, levels = c("0-9 years","10-19 years" ,"20-29 year", "30-39 years", "40-49 years", "50-59 years", "60-69 years", "70-79 years", "80-89 years", "90 years and over"))) %>%
  arrange(age_group)

age_group_cov_hb_ans <- df_cov_hb_ans %>% 
  filter(age_group != "All ages") %>% 
  mutate(age_group = factor(age_group, levels = c("Under 5","5 - 14" ,"15 - 44", "45 - 64", "65 - 74", "75 - 84", "85 and over")
  )) %>%
  arrange(age_group)



age_group_cov_hscp_ans <- df_cov_hscp_ans %>% 
  filter(age_group != "All ages") %>% 
  mutate(age_group = factor(age_group, levels = c("Under 5","5 - 14" ,"15 - 44", "45 - 64", "65 - 74", "75 - 84", "85 and over")
  )) %>%
  arrange(age_group)

age_ane_hscp_ans <- df_ane_hscp_ans %>% 
  filter(age_group != "All ages") %>% 
  mutate(age_group = factor(age_group, levels = c("Under 5","5 - 14" ,"15 - 44", "45 - 64", "65 - 74", "75 - 84", "85 and over")
  )) %>%
  arrange(age_group)

```

# Graph Sample
```{r}
# Graph Sample
age_group_cov_hb_ans %>% 
  group_by(age_group) %>% 
  summarise(count = n()) %>% 
  ggplot()+
  aes(x = age_group, y = count, fill = age_group)+
  geom_bar(stat = "identity")+
  labs(
    title = "This is a Title",
    subtitile = "This is a subtitle"
    ) +
  xlab("X label") +
  ylab("Y label")

```


```{r}
# make_file_names <- function(x) paste0(save_path,x,".csv")
# save_csv <- function(x) write_csv(obj_list[[x]],file_name[[x]])
# 
# target_directory <- here("raw_data/test/")
# 
# 
# save_path = paste0("..\\phs_rshiny_dashboard_grp1\\raw_data\\test\\")
# name_pattern <- grep("df_",names(.GlobalEnv),value=TRUE)
# obj_list     <- do.call("list",mget(name_pattern))
# file_name      <- make_file_names(names(obj_list))
# 
# for (i in seq_along(names(obj_list))) save_csv(i)
# 
# 
# 
#   dataframes_list <- as.list( ls.str(mode = "list"))
#   dataframes_list_csv <- paste0(dataframes_list, ".csv")
#   file_path = paste0(save_path, dataframes_list_csv)
# 
# for (x in 1: length(dataframes_list)){
#   data_frame_name <- paste0(dataframes_list[x], ".csv")
#   data_frame_file_path <- paste0(save_path,data_frame_name)
#   write.csv(as.character(data_frame_name), as.character(data_frame_file_path), row.names = FALSE)
# 
# }
# 
# write.csv(df_sco_dov_daily_deprivation,"..\\phs_rshiny_dashboard_grp1\\raw_data\\df_sco_dov_daily_deprivation.csv", row.names = FALSE)
# #
# #
# #
# #
# file_path = paste0(save_path,file_name)
# #
# #
# write.csv(age_ane_hscp_ans,save_path + file_name+".csv", row.names = FALSE)

```




# Redundant Code Dumping Ground
```{r}

```









