---
title: "Covid Hospital Activity Analysis"
output: html_notebook
---

```{r}
# How does Covid affect hospital activity?
# Was there a change post Q1 2020?
```


```{r, echo=FALSE, message=FALSE, results='hide'}
library(tidyverse)
library(sf)
library(janitor)
library(jsonlite)
library(lubridate)
library(rgdal)
library(broom)
require(readr)
require(here)
```
```{r}
day_cum_case <- read_csv("clean_data/df_day_cum_cov.csv")

nor_ha_ans <- read_csv("clean_data/df_ha_ans.csv")
cov_ha_ans <- read_csv("clean_data/df_cov_hb_ans.csv")
df_hospital_location <- read_csv("clean_data/df_hospital_location.csv")
```




```{r}
cov_eps <- cov_ha_ans %>% 
  mutate(quart_year = paste0(year, "Q", quarter)) %>% 
  arrange(quart_year) %>% 
  group_by(quart_year) %>% 
  summarise(cov_eps = sum(number_admissions)/1000)

nor_eps <- nor_ha_ans %>% 
    mutate(quart_year = paste0(year, "Q", quarter)) %>% 
  group_by(quart_year, year, quarter) %>% 
  summarise(nor_eps = sum(episodes)/1000)

total_eps <- left_join(nor_eps, cov_eps, by = "quart_year") %>% 
  mutate(cov_eps = coalesce(cov_eps,0),
         quart_year = str_sub(quart_year, 3,6))

total_eps %>% 
  ggplot()+
  geom_bar(aes(x = quart_year, y = nor_eps), stat = "identity", alpha = 0.7)+
  geom_bar(aes(x = quart_year, y = cov_eps), stat = "identity", fill = "red", alpha = 0.75)+
    theme(axis.text.x = element_text(angle = 45))+
  labs(title = "Hospital Admission Trend",
       subtitle = "Total Hospital Admission (Grey) vs Covid Related Admission(Red)")+
  xlab("Time (Year/Quarter)")+
  ylab("Admission count (per thousand)")




```


```{r}
test <- cov_ha_ans %>% 
  filter(!grepl("All",admission_type))
  
```



# Dump
```{r}
day_case <- day_cum_case %>%
  mutate(year = year(date),
         month = month(date),
           week = week(date))

cov_case_rate <- day_case %>%
  group_by(year,month) %>%
  mutate(rate = daily_cases - lag(daily_cases)) %>%
  slice(-1)


cov_case_rate %>%
  mutate(month = factor(month)) %>%
  ggplot()+
  aes(x = date, y = daily_cases )+
  geom_bar(stat = "identity")+
  labs(
    title = "Daily Covid Cases Per month"
  )
# 
# 
# cov_case_season <- day_case %>% 
#   mutate(season = case_when(
#     month == 1 & month == 2 & month == 12 ~ "winter",
#     month == 3 & month == 4 & month == 5 ~ "spring",    
#     month == 6 & month == 7 & month == 8 ~ "summer",
#     month == 9 & month == 10 & month == 11 ~ "autumn",
#     ))




```

```{r}

df_hospital_location <- read_csv("clean_data/df_hospital_location.csv")
df_day_trend_hb <- read_csv("clean_data/df_day_trend_hb.csv")

hospital_location_func <- function(df, key_col){
            df <- df %>% 
            # Select location & hb as forgein keys
            # Join location_name, longitude & latitude to the main dataframe
            left_join(df_hospital_location %>% select(key_col, location_name, longitude, latitude),
            by = c(key_col),
            all.x = TRUE)
            
            return(df)
}



day_trend_hb <- hospital_location_func(df_day_trend_hb, "hb") %>%
  group_by(date, hb, hb_name) %>% 
  summarise(daily_positive = sum(daily_positive))

day_trend_hb %>% 
  ggplot()+
  aes(x = date, y = daily_positive)+
  geom_bar(stat = "identity")+
    labs(
    title = "Daily Trend Cases"
  )
  
day_trend_hb %>% 
  filter(hb_name == "NHS Borders") %>% 
  ggplot()+
  aes(x = date, y = daily_positive)+
  geom_bar(stat = "identity")+
  labs(
    title = "Daily Trend Cases Per Hospital"
  )


# Suggestion Can do a Hospital Filter
# Do a infection(count), death count,  infection rate, death rate
```


